service_port_name: "http"
params: "30m"
hub: "istio"
tag: "1.18.0"
perf_client: "fortio"
test_wait: "180"
server_scale: "3"
namespace_scale: "4"
istioctl_path: "istioctl"
clusters:
- context: "gke_gihanson-perf"
