service_port_name: "http"
params: "--concurrency 1 --output-format json --rps 200 --duration 60"
final_result: "/tmp/results.txt"
hub: "harbor.hawton.haus/daniel"
tag: "ambient"
linkerd: true
clusters:
- context: "kind-ambient"
  k8s_type: "kind"
  result_file: "/tmp/results-ambient-kind.csv"
- context: "daniel_hawton@daniel-ambient-perf.us-west-2.eksctl.io"
  k8s_type: "aws"
  result_file: "/tmp/results-ambient-aws.csv"
- context: "gke_solo-test-236622_us-west1-c_daniel-istio"
  k8s_type: "gcp"
  result_file: "/tmp/results-ambient-gke.csv"
