service_port_name: "http"
params: "-c 1 -qps 2 -t 10m"
hub: "istio"
tag: "1.18.0-alpha.0"
perf_client: "fortio"
test_wait: "180"
server_scale: "10"
istioctl_path: "istioctl"
clusters:
- context: "gke_us-central1-c_gihanson-ambient"
