apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-server
spec:
  ports:
  - name: benchmark
    port: 5201
    protocol: TCP
  selector:
    app: benchmark-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchmark-server
  name: benchmark-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-server
  template:
    metadata:
      labels:
        app: benchmark-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "benchmark-client"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: server
        image: us-west3-docker.pkg.dev/solo-test-236622/daniel-solo/iperf3:latest
        imagePullPolicy: Always
        command: ["iperf3"]
        args:
        - -s
        ports:
        - containerPort: 5201
          name: benchmark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchmark-client
  name: benchmark-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-client
  template:
    metadata:
      labels:
        app: benchmark-client
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "benchmark-server"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: client
        image: us-west3-docker.pkg.dev/solo-test-236622/daniel-solo/iperf3:latest
        imagePullPolicy: Always
        command: ["/bin/sleep"]
        args:
        - 365d