apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark-client
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-server
spec:
  ports:
  - name: benchmark
    port: 8078
    protocol: TCP
  selector:
    app: benchmark-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchmark-server
  name: benchmark-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-server
  template:
    metadata:
      labels:
        app: benchmark-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "benchmark-client"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: server
        image: gcr.io/solo-oss/ambient-performance/fortio:latest
        imagePullPolicy: IfNotPresent
        command: ["fortio"]
        args:
        - tcp-echo
        ports:
        - containerPort: 8078
          name: benchmark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchmark-client
  name: benchmark-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-client
  template:
    metadata:
      labels:
        app: benchmark-client
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "benchmark-server"
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: benchmark-client
      containers:
      - name: client
        image: gcr.io/solo-oss/ambient-performance/fortio:latest
        imagePullPolicy: Always
        command: ["/bin/sleep"]
        args:
        - 365d
