apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: benchmark-server
  annotations:
    istio.io/for-service-account: benchmark-server
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE